// The Algorithm desk's hovers: what each column, tile and panel means (the template's help[key])
export const DESK_HELP: Record<string, string> = {
  record: 'Won-lost-pushed (sorts by the share won)',
  streak: 'The current run: the latest graded bets in a row that won (W) or lost (L), pushes skipped',
  profit: 'Units won or lost, stakes included',
  roi: 'Return on the units staked: profit ÷ staked',
  open: 'Bets placed on games not played yet',
  available: "What's left to bet with: the bankroll (1,000 to start, plus what's been won or lost, plus 1,000 for each rebuy) less the stakes on open bets, as at a sportsbook",
  intent: 'Edge: bets where it saw value. Action: no edge, placed only for the data (every market gets a bet). The model is judged on the edge record',
  atRisk: "The stakes on every open bet, started or not: out of the balance until they're graded",
  live: 'Bets on games under way right now, with the score (ESPN, every minute); graded on the next run after the game ends',
  test: "How the ratings did on games they hadn't seen yet: winners picked right, and how far off the margins and totals were on average",
  sport: 'The league',
  game: 'Away @ home',
  start: 'When the game starts',
  market: 'Spread, total (over/under) or moneyline',
  pick: 'The side it took',
  odds: "The sportsbook's price when it bet (American odds)",
  units: 'Stake: 0.5 units at no edge, up to 3 at an 8% expected return',
  p: "The chance it gave this side: the model's own, pulled toward the book's by how much that market trusts the model",
  fair: "The sportsbook's chance for this side, its cut (the vig) taken out",
  ev: "Expected return per unit at its chance and the book's odds",
  final: 'The final score',
  result: 'Won, lost or pushed, and what it paid',
  calibLabel: 'The chance it gave its picks, in 5-point bands',
  n: 'Bets graded in the band',
  said: 'The average chance it gave them (a bet whose premise broke in the game counts less: see Why)',
  was: 'How often they actually won (close to "Said" is honest)',
  k: "Learning rate: how far one game's surprise moves a team's rating (0.08 moves it 8% of the miss)",
  hfa: "Home edge: how much playing at home is worth, in the sport's scoring unit (points, goals, runs)",
  revert: "Season carryover: how much of a team's rating carries into the next season (the rest drifts back to average)",
  kO: "Scoring rate: how fast a team's points-for and points-against rates move with each game",
  sigma: 'Margin spread: how far real margins land from what it expects (one standard deviation; bigger means less sure)',
  sigmaT: 'Total spread: the same for game totals',
  trust: "How much each market counts the model against the sportsbook: 0 the book's alone, 1 the model's alone (starts at 0.5; refit on the market's graded bets once 40 are; * not yet)",
  history: 'Finished games the ratings are built on',
  why: "Why it won or lost, from the game's box score and story: what broke the bet's premise in the game (a quarterback replaced, a top player's minutes or snaps cut short, a goalie pulled, a starter gone early: ! marks one, and such a bet counts less in what the desk learns), overtime or a blowout, and how far off its call was. Hover for the story; the link opens ESPN's recap",
  disrupted: "Graded bets whose premise broke in the game (a starter hurt, a goalie pulled...): they count less in the trust fit and the calibration, in full in the record",
  prop: "The player stat (DraftKings' main line; its price isn't in the free feed, so each side's is estimated from the player's own record at the line with -110's cut)",
  rows: 'Player games its projection was fit and checked on',
  mae: "On the last 30% of the history (never fit on): how far its projection missed on average, against a plain season average's miss",
  overLine: "On the same held-out games, at a line at each player's median so far: its chance of going over against what happened (log loss, lower is better), against the player's own over-rate",
  sideHit: 'On those lines, how often the side it leaned (by 5 points or more) was right',
  matchups: "The matchup terms (matchups.mjs), each kept only if the held-out games' over/under log loss is lower with it: the role split (the defense against his role on his team: an NFL WR1, WR2, WR3, TE1, RB1; an NBA starter or bench), pulled toward its position number by k games; the defense's pass or run funnel (how much more or less its opponents pass than nflverse's xpass expects, in neutral situations, against their own lean) and pace (volume); the share of targets it allows his position. The gain: the held-out log loss without it less with it",
  propSettings: 'Its fitted settings: K (games of pull toward his position), recent weight, opponent power, game-script power, context size, spread (r: lower is wider)',
  propTrust: "How much the prop type counts its projection against the player's own record (starts 0.5; refit on its graded props once 40 are; * not yet)",
  clv: "Closing-line value: how its bets' lines and prices compare with where the market closed, the market's last word before the game. The share that beat the close (a better line, or the same line at a better chance), and the mean expected return at the closing chance. The early skill signal: a few dozen results are mostly luck, but beating the close shows an edge from the first bets on; the trust in the model leans on it until results pile up",
  betClv: "Its closing-line value: the points its line beat the close by (a spread, a total or a prop), else the chance its side gained on it; green when it beat the close",
  book: "The sportsbook every bet is priced and placed at, its lines and prices (BOOK in libs/ranker/scripts/model/leagues.mjs). The fair chance each side is weighed against is Pinnacle's, its vig taken out, where Pinnacle has the line; else the book's own",
  betBook: "The book it's priced and placed at, and where its fair chance came from (Pinnacle's line, or the book's own prices)",
  credits: "The Odds API's credits this cycle (20,000 a month; the cycle assumed to run a month from the first call): spent by feature, what's left, and what each live feature may spend today. 2,000 are held back; history (the backtest) has its own 6,000. As credits run low the backtest stops first, then props, then lines; without them the desk prices from ESPN's free board, the same book's",
  btBets: 'Games in the backtest: real lines from The Odds API, each game bet at its last snapshot before it started (the close)',
  btTrust: "The trust fitted on those closing bets: how much the model adds to the market's own number (0: nothing; the live runs start from it)",
  btClose: "Return on the closing bets at the desk's stakes, every market bet, at that trust",
  btEarly: 'Return on the same games bet at an early line (a mid-week or morning snapshot), at that trust. Flattered: the model knows things the early line didn\'t yet (who actually started)',
  btBeat: "Of the early bets, the share that beat the close (the line moved toward the side it took)",
  btLoss: "The model's log loss on the results less the market's, at the close: below 0, the model's chances were sharper than the market's",
  btAnchor: "The market's log loss with the book's own prices less with Pinnacle's: above 0, Pinnacle's is the better fair chance",
  term: "What it weighs beyond the ratings (hover a name for its unit): rest and the schedule's grind, travel, starters and bullpens, weather and air, ballparks, the officials, expected goals and neutral-script EPA, and last season's numbers from the ranker",
  on: 'What it moves: the margin (toward the side it names) or the game total',
  size: "Its fitted size, in the sport's scoring unit per unit of the term (hover the name for the unit); refit every run on every game before, pulled toward 0 unless the games bear it out",
  kept: 'Kept if the held-out games were predicted better with it; left out (size 0) if not',
  games: 'Games in the history where it applied',
  gain: "How much tighter its predictions of games it hadn't seen were with this term than without, in percent (negative: it hurt, so it's left out)",
};
