import { SPORT } from '@sport/sport';

// The ranking data (generated by each sport's `npm run <sport>:update-data`) is served as JSON files
// next to the app (angular.json copies apps/<sport>/src/StaticData/**/*.json to data/) instead of
// being bundled into it. main.ts loads a season before starting the app, so everything that reads DATA
// can use it right away; the year selector loads another season in place (PositionService.setSeason).
// (skill-players.json, plus any files the sport lists in SPORT.dataFiles, under their keys)
export interface AppData {
  skillPlayers: unknown;
  [key: string]: unknown;
}

export const DATA = {} as AppData;

// The season updated every night, and the finished seasons kept alongside it (newest first). A
// past season lives in StaticData/seasons/<year>/ (`SEASON=<year> npm run <sport>:update-data`).
export const CURRENT_SEASON = SPORT.currentSeason;
export const SEASONS = Array.from({ length: CURRENT_SEASON - SPORT.firstSeason + 1 }, (_, i) => CURRENT_SEASON - i);

// The current season is still being played (until the sport's currentSeasonEnds date). Once it's over
// it reads like any finished season, by its name, until the yearly rollover makes the next one current.
export const SEASON_LIVE = Date.now() < new Date(SPORT.currentSeasonEnds + 'T00:00:00').getTime();
export const isLiveSeason = (season: number) => season === CURRENT_SEASON && SEASON_LIVE;

// The season DATA holds, and a count that goes up with every load (for caches keyed on the data)
export let dataSeason = CURRENT_SEASON;
export let dataVersion = 0;

const FILES: Record<string, string> = {
  skillPlayers: 'skill-players.json',
  ...SPORT.dataFiles,
};

// A season from a shared link (?season=2024), if it's one we have. Refreshing the page goes back to
// the current season (and takes ?season out of the address); opening a link still lands on its year.
export function linkedSeason(): number {
  const navigation = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming | undefined;
  if (navigation?.type === 'reload') {
    const url = new URL(location.href);
    if (url.searchParams.has('season')) {
      url.searchParams.delete('season');
      history.replaceState(null, '', url);
    }
    return CURRENT_SEASON;
  }
  const linked = Number(new URLSearchParams(location.search).get('season'));
  return SEASONS.includes(linked) ? linked : CURRENT_SEASON;
}

// The current season is fetched with "no-cache" (it still uses the browser's copy, but checks with
// the server first, so a nightly data update shows up on the next visit); a finished season never
// changes, so the browser's copy is used as is
export async function loadData(season = CURRENT_SEASON): Promise<void> {
  Object.assign(DATA, await fetchSeason(season));
  dataSeason = season;
  dataVersion++;
}

// Run fn with another season's files in DATA, and dataSeason saying so (a sport building another
// season's rows reads both: the NFL only blends preseason grades into the season being played), then
// put the loaded season back
export function withSeason<T>(season: number, data: AppData, fn: () => T): T {
  const loaded = { ...DATA };
  const loadedSeason = dataSeason;
  Object.assign(DATA, data);
  dataSeason = season;
  try {
    return fn();
  } finally {
    Object.assign(DATA, loaded);
    dataSeason = loadedSeason;
  }
}

// A season's files, without loading them into DATA (the player card reads other seasons this way,
// leaving the table on its own)
export async function fetchSeason(season: number): Promise<AppData> {
  const entries = await Promise.all(
    Object.entries(FILES).map(async ([key, file]) => [key, await fetchSeasonFile(season, file)] as const),
  );
  return Object.fromEntries(entries) as unknown as AppData;
}

// One file of a season's data (also comps.json, the similar seasons of a finished one)
export async function fetchSeasonFile<T = unknown>(season: number, file: string): Promise<T> {
  const current = season === CURRENT_SEASON;
  const dir = current ? 'data' : `data/seasons/${season}`;
  const res = await fetch(`${dir}/${file}`, { cache: current ? 'no-cache' : 'default' });
  if (!res.ok) throw new Error(`Could not load ${season} ${file}: ${res.status}`);
  return expandRows(await res.json()) as T;
}

// A file whose rows repeated across tabs are stored once (libs/ranker/scripts/shared-rows.mjs: MMA's
// fighters, in the pound-for-pound list and their division alike) put back together; any other as it is
function expandRows(file: unknown): unknown {
  const shared = (file as { $shared?: Record<string, object> } | null)?.$shared;
  if (!shared) return file;
  const { $shared: _, ...tabs } = file as Record<string, { $id?: string }[]>;
  return Object.fromEntries(
    Object.entries(tabs).map(([tab, rows]) => [tab, rows.map(({ $id, ...own }) => ($id === undefined ? own : { ...shared[$id], ...own }))]),
  );
}
