// The ranking data (generated by `npm run update-data`) is served as JSON files next to the app
// (angular.json copies src/StaticData/*.json to data/) instead of being bundled into it. main.ts
// loads them before starting the app, so everything that reads DATA can use it right away.
export interface AppData {
  games: unknown;
  subjective: unknown;
  teamGrades: unknown;
  dataGrades: unknown;
  skillPlayers: unknown;
}

export const DATA = {} as AppData;

const FILES: Record<keyof AppData, string> = {
  games: 'games.json',
  subjective: 'subjective.json',
  teamGrades: 'team-grades.json',
  dataGrades: 'data-grades.json',
  skillPlayers: 'skill-players.json',
};

// "no-cache" still uses the browser's copy, but checks with the server first, so a nightly data
// update shows up on the next visit
export async function loadData(): Promise<void> {
  const entries = await Promise.all(
    Object.entries(FILES).map(async ([key, file]) => {
      const res = await fetch(`data/${file}`, { cache: 'no-cache' });
      if (!res.ok) throw new Error(`Could not load ${file}: ${res.status}`);
      return [key, await res.json()] as const;
    }),
  );
  Object.assign(DATA, Object.fromEntries(entries));
}
