// The ranking data (generated by `npm run update-data`) is served as JSON files next to the app
// (angular.json copies src/StaticData/**/*.json to data/) instead of being bundled into it. main.ts
// loads a season before starting the app, so everything that reads DATA can use it right away; the
// year selector loads another season in place (see PositionService.setSeason).
export interface AppData {
  games: unknown;
  subjective: unknown;
  teamGrades: unknown;
  dataGrades: unknown;
  skillPlayers: unknown;
}

export const DATA = {} as AppData;

// The season updated every night, and the finished seasons kept alongside it (newest first). A
// past season lives in src/StaticData/seasons/<year>/ (`SEASON=<year> npm run update-data`).
export const CURRENT_SEASON = 2026;
// Back to 2000 (stats not recorded yet in a season, like drops before 2018, are hidden for it)
export const SEASONS = Array.from({ length: CURRENT_SEASON - 2000 + 1 }, (_, i) => CURRENT_SEASON - i);

// The season DATA holds, and a count that goes up with every load (for caches keyed on the data)
export let dataSeason = CURRENT_SEASON;
export let dataVersion = 0;

const FILES: Record<keyof AppData, string> = {
  games: 'games.json',
  subjective: 'subjective.json',
  teamGrades: 'team-grades.json',
  dataGrades: 'data-grades.json',
  skillPlayers: 'skill-players.json',
};

// A season from a shared link (?season=2024), if it's one we have
export function linkedSeason(): number {
  const linked = Number(new URLSearchParams(location.search).get('season'));
  return SEASONS.includes(linked) ? linked : CURRENT_SEASON;
}

// The current season is fetched with "no-cache" (it still uses the browser's copy, but checks with
// the server first, so a nightly data update shows up on the next visit); a finished season never
// changes, so the browser's copy is used as is
export async function loadData(season = CURRENT_SEASON): Promise<void> {
  const current = season === CURRENT_SEASON;
  const dir = current ? 'data' : `data/seasons/${season}`;
  const entries = await Promise.all(
    Object.entries(FILES).map(async ([key, file]) => {
      const res = await fetch(`${dir}/${file}`, { cache: current ? 'no-cache' : 'default' });
      if (!res.ok) throw new Error(`Could not load ${season} ${file}: ${res.status}`);
      return [key, await res.json()] as const;
    }),
  );
  Object.assign(DATA, Object.fromEntries(entries));
  dataSeason = season;
  dataVersion++;
}
