import { QbBoxStats, QbPlayByPlay, StaticPlayerData } from 'app/types';
import { DATA } from './data';

// Loaded by main.ts before the app starts (see data.ts)
const gamesJson = DATA.games;
const subjective = DATA.subjective;
const teamGradesJson = DATA.teamGrades;
const dataGradesJson = DATA.dataGrades;

// games.json is generated from ESPN box scores by `npm run update-data` — don't edit it by hand.
// team-grades.json holds the preseason team grades (0 = F ... 12 = A+), keyed by team logo name.
// subjective.json holds preseason per-QB scores, keyed by ESPN player id.
// data-grades.json (also generated by `npm run update-data`) grades the same things from this
// season's stats; the two are blended, leaning on the stats more with every game played.
interface GameData {
  id: number;
  name: string;
  teamLogo: string;
  wins: number;
  losses: number;
  ties: number;
  lastFive: number[];
  starts: Record<string, number>;
  // From ESPN's injury report: Out, Doubtful or Injured Reserve
  injured: boolean;
  // ESPN season box stats, fetched in the same nightly run as the results (null: no stats yet)
  box?: QbBoxStats | null;
  advanced: {
    epaPerPlay: number | null;
    cpoe: number | null;
    successRate: number | null;
    fantasyStd: number;
    receptions: number;
    pressureToSack: number | null;
    badThrowPct: number | null;
    timeToThrow: number | null;
    adot: number | null;
    aggressiveness: number | null;
    // The play-by-play stats without garbage time (win probability under 10% or over 90%)
    competitive?: QbPlayByPlay;
  } | null;
}

export interface TeamGrades {
  weapons: number;
  oline: number;
  coaching: number;
}

// Per-QB scores. Team grades, defense (normally from the Defenses rankings) and injured
// (normally from ESPN's injury report) can be overridden here for a single QB.
type SubjectiveScores = Pick<StaticPlayerData, 'responsibility'> &
  Partial<TeamGrades> & { name?: string; defense?: number; injured?: boolean };

const games = gamesJson as unknown as GameData[];
const scores = subjective as Record<string, SubjectiveScores>;
const teamGrades = teamGradesJson as Record<string, TeamGrades>;

interface DataGrades {
  teams: Record<string, { games: number; oline: number; weapons: number }>;
  qbs: Record<string, { games: number; responsibility: number }>;
}
const dataGrades = dataGradesJson as unknown as DataGrades;

// Share of a grade that comes from this season's stats, rising to all of it by 14 games:
// 17% after 1 game, 35% after 3, 56% after 6, 68% after 8, 80% after 10, 90% after 12, 100% at 14+.
// (A gentle curve, (games / 14) ^ 0.68, so the preseason view still leads early in the season.)
const FULL_WEIGHT_GAMES = 14;
export function dataWeight(games: number): number {
  return games > 0 ? Math.min(1, (games / FULL_WEIGHT_GAMES) ** 0.68) : 0;
}

// Preseason grade blended with the stats grade, as a whole grade (0-12)
export function blendGrade(preseason: number, fromData: number | undefined, games: number): number {
  if (fromData === undefined || fromData === null) return preseason;
  return Math.round(preseason + (fromData - preseason) * dataWeight(games));
}

// Preseason coaching grade per team; the app blends it with the Head Coaches rankings
export function preseasonCoaching(teamLogo: string): number {
  return (teamGrades[teamKey(teamLogo)] ?? { coaching: 6 }).coaching;
}

// Preseason weapons grade per team; the app blends it with the RB, WR and TE rankings
export function preseasonWeapons(teamLogo: string): number {
  return (teamGrades[teamKey(teamLogo)] ?? { weapons: 6 }).weapons;
}

// Preseason O-line grade per team; the app blends it with the Offensive Lines rankings
export function preseasonOline(teamLogo: string): number {
  return (teamGrades[teamKey(teamLogo)] ?? { oline: 6 }).oline;
}

// Team games played this season (from the stats grades)
export function teamGamesPlayed(teamLogo: string): number {
  return dataGrades.teams[teamKey(teamLogo)]?.games ?? 0;
}

// "../assets/NFL_Icons/Bills.png" -> "Bills"
export function teamKey(teamLogo: string): string {
  return teamLogo.split('/').pop()!.replace('.png', '');
}

// Team grades for a logo; average (C, 6) if the team is missing. Weapons and O-line are
// blended with this season's stats; coaching is the preseason grade (see preseasonCoaching)
export function gradesForTeam(teamLogo: string): TeamGrades {
  const preseason = teamGrades[teamKey(teamLogo)] ?? { weapons: 6, oline: 6, coaching: 6 };
  const stats = dataGrades.teams[teamKey(teamLogo)];
  const games = stats?.games ?? 0;
  return {
    weapons: blendGrade(preseason.weapons, stats?.weapons, games),
    oline: blendGrade(preseason.oline, stats?.oline, games),
    coaching: preseason.coaching,
  };
}

// Static Data
export const StaticData: StaticPlayerData[] = games.map((game) => {
  const { name, defense, injured, coaching, ...playerScores } = scores[game.id];
  const qbStats = dataGrades.qbs[game.id];

  return {
    id: game.id,
    name: name ?? game.name,
    teamLogo: game.teamLogo,
    wins: game.wins,
    losses: game.losses,
    ties: game.ties,
    lastFive: game.lastFive,
    epaPerPlay: game.advanced?.epaPerPlay ?? null,
    cpoe: game.advanced?.cpoe ?? null,
    successRate: game.advanced?.successRate ?? null,
    fantasyStd: game.advanced?.fantasyStd ?? null,
    receptions: game.advanced?.receptions ?? 0,
    pressureToSack: game.advanced?.pressureToSack ?? null,
    badThrowPct: game.advanced?.badThrowPct ?? null,
    timeToThrow: game.advanced?.timeToThrow ?? null,
    adot: game.advanced?.adot ?? null,
    aggressiveness: game.advanced?.aggressiveness ?? null,
    competitive: game.advanced?.competitive ?? null,
    starts: game.starts,
    box: game.box ?? null,
    injured: injured ?? game.injured ?? false,
    // Placeholder until the Defenses rankings grade the team
    defense: defense ?? 6,
    defenseOverride: defense,
    ...gradesForTeam(game.teamLogo),
    // Placeholder until the Head Coaches rankings grade the team
    coachingOverride: coaching,
    ...playerScores,
    responsibility: blendGrade(playerScores.responsibility, qbStats?.responsibility, qbStats?.games ?? 0),
  };
});
