import type { SkillPlayer } from 'app/positions';
import { QbBoxStats, QbPlayByPlay, StaticPlayerData } from 'app/types';
import { DATA } from './data';

// games.json is generated from ESPN box scores by `npm run update-data` — don't edit it by hand.
// team-grades.json holds the preseason team grades (0 = F ... 12 = A+), keyed by team logo name.
// subjective.json holds preseason per-QB scores, keyed by ESPN player id.
// data-grades.json (also generated by `npm run update-data`) grades the same things from this
// season's stats; the two are blended, leaning on the stats more with every game played.
interface GameData {
  id: number;
  name: string;
  teamLogo: string;
  wins: number;
  losses: number;
  ties: number;
  lastFive: number[];
  starts: Record<string, number>;
  // From ESPN's injury report: Out, Doubtful or Injured Reserve
  injured: boolean;
  injuryStatus?: string;
  // ESPN season box stats, fetched in the same nightly run as the results (null: no stats yet)
  box?: QbBoxStats | null;
  advanced: {
    epaPerPlay: number | null;
    cpoe: number | null;
    successRate: number | null;
    fantasyStd: number;
    receptions: number;
    pressureToSack: number | null;
    badThrowPct: number | null;
    timeToThrow: number | null;
    adot: number | null;
    aggressiveness: number | null;
    // The play-by-play stats without garbage time (win probability under 10% or over 90%)
    competitive?: QbPlayByPlay;
  } | null;
}

export interface TeamGrades {
  weapons: number;
  oline: number;
  coaching: number;
}

// Per-QB preseason scores: Responsibility (blended with this season's stats below), plus an optional
// display name and injured flag (normally from ESPN's injury report) for a single QB
type SubjectiveScores = Pick<StaticPlayerData, 'responsibility'> & { name?: string; injured?: boolean };

// Read from DATA on every call, since the year selector can load another season (see data.ts)
const games = () => DATA.games as GameData[];
const scores = () => DATA.subjective as Record<string, SubjectiveScores>;
const teamGrades = () => DATA.teamGrades as Record<string, TeamGrades>;

interface DataGrades {
  // newCoach: a first-year head coach (no NFL head-coaching games before this season)
  teams: Record<string, { games: number; oline: number; weapons: number; newCoach?: boolean }>;
  qbs: Record<string, { games: number; responsibility: number }>;
}
const dataGrades = () => DATA.dataGrades as DataGrades;

// Share of a grade that comes from this season's stats, rising to all of it by 14 games:
// 17% after 1 game, 35% after 3, 56% after 6, 68% after 8, 80% after 10, 90% after 12, 100% at 14+.
// (A gentle curve, (games / 14) ^ 0.68, so the preseason view still leads early in the season.)
const FULL_WEIGHT_GAMES = 14;
export function dataWeight(games: number): number {
  return games > 0 ? Math.min(1, (games / FULL_WEIGHT_GAMES) ** 0.68) : 0;
}

// Preseason grade blended with the stats grade, before rounding (it's curved next)
function blendScore(preseason: number, fromData: number | undefined, games: number): number {
  if (fromData === undefined || fromData === null) return preseason;
  return preseason + (fromData - preseason) * dataWeight(games);
}

// Preseason coaching grade per team; the app blends it with the Head Coaches rankings. A first-year
// head coach has no track record, so he starts at a neutral C (6) whatever the team's grade says.
export function preseasonCoaching(teamLogo: string): number {
  if (dataGrades().teams[teamKey(teamLogo)]?.newCoach) return 6;
  return (teamGrades()[teamKey(teamLogo)] ?? { coaching: 6 }).coaching;
}

// Preseason weapons grade per team; the app blends it with the RB, WR and TE rankings
export function preseasonWeapons(teamLogo: string): number {
  return (teamGrades()[teamKey(teamLogo)] ?? { weapons: 6 }).weapons;
}

// Preseason O-line grade per team; the app blends it with the Offensive Lines rankings
export function preseasonOline(teamLogo: string): number {
  return (teamGrades()[teamKey(teamLogo)] ?? { oline: 6 }).oline;
}

// Team games played this season (from the stats grades)
export function teamGamesPlayed(teamLogo: string): number {
  return dataGrades().teams[teamKey(teamLogo)]?.games ?? 0;
}

// "../assets/NFL_Icons/Bills.png" -> "Bills"
export function teamKey(teamLogo: string): string {
  return teamLogo.split('/').pop()!.replace('.png', '');
}

// The loaded season's QBs, with their blended and curved Responsibility
function qbData(): StaticPlayerData[] {
  const grades = dataGrades();
  const qbs: StaticPlayerData[] = games().map((game) => {
    // A QB missing from subjective.json starts from a neutral C
    const { name, injured, ...playerScores } = scores()[game.id] ?? { responsibility: 6 };
    const qbStats = grades.qbs[game.id];

    return {
      id: game.id,
      name: name ?? game.name,
      teamLogo: game.teamLogo,
      wins: game.wins,
      losses: game.losses,
      ties: game.ties,
      lastFive: game.lastFive,
      epaPerPlay: game.advanced?.epaPerPlay ?? null,
      cpoe: game.advanced?.cpoe ?? null,
      successRate: game.advanced?.successRate ?? null,
      fantasyStd: game.advanced?.fantasyStd ?? null,
      receptions: game.advanced?.receptions ?? 0,
      pressureToSack: game.advanced?.pressureToSack ?? null,
      badThrowPct: game.advanced?.badThrowPct ?? null,
      timeToThrow: game.advanced?.timeToThrow ?? null,
      adot: game.advanced?.adot ?? null,
      aggressiveness: game.advanced?.aggressiveness ?? null,
      competitive: game.advanced?.competitive ?? null,
      starts: game.starts,
      box: game.box ?? null,
      injured: injured ?? game.injured ?? false,
      injuryStatus: game.injuryStatus,
      ...playerScores,
      responsibility: blendScore(playerScores.responsibility, qbStats?.responsibility, qbStats?.games ?? 0),
    };
  });

  // Responsibility on a curve across the QBs: the highest blended score grades A+, the lowest F
  const ranked = [...qbs].sort((a, b) => b.responsibility - a.responsibility);
  const last = Math.max(ranked.length - 1, 1);
  ranked.forEach((qb, rank) => (qb.responsibility = Math.round(12 * (1 - rank / last))));
  return qbs;
}

// The QBs as rows of the shared rankings table (the same shape as every other tab's units): ESPN box
// stats, record and recent results, the nflverse play-by-play stats (plus their no-garbage-time copy),
// and the blended, curved Responsibility grade. QBs with no ESPN stats this season yet are left out.
export function buildQbUnits(): SkillPlayer[] {
  return qbData()
    .filter((qb) => !!qb.box)
    .map((qb) => {
      const box = qb.box!;
      const ties = qb.ties ?? 0;
      const starts = qb.wins + qb.losses + ties;
      return {
        id: qb.id,
        gsisId: `QB-${qb.id}`,
        name: qb.name,
        teamLogo: qb.teamLogo,
        games: box.games,
        injured: qb.injured,
        injuryStatus: qb.injuryStatus,
        lastFive: qb.lastFive,
        starts: qb.starts,
        competitive: qb.competitive ?? undefined,
        stats: {
          wins: qb.wins,
          losses: qb.losses,
          ties,
          winPct: starts ? (qb.wins + ties * 0.5) / starts : null,
          compPct: box.compPercent,
          passYards: box.passYards,
          rushYards: box.rushYards,
          passTds: box.passTd,
          rushTds: box.rushTd,
          ints: box.ints,
          fumbles: box.fumLost,
          ypa: box.ypa,
          rating: box.rating,
          epaPerPlay: qb.epaPerPlay,
          successRate: qb.successRate,
          cpoe: qb.cpoe,
          pressureToSack: qb.pressureToSack,
          badThrowPct: qb.badThrowPct,
          timeToThrow: qb.timeToThrow,
          adot: qb.adot,
          aggressiveness: qb.aggressiveness,
          fantasyStd: qb.fantasyStd,
          receptions: qb.receptions,
          responsibility: qb.responsibility,
        } as SkillPlayer['stats'],
      };
    });
}
