import { StaticPlayerData } from 'app/types';

// Static Data
export let StaticData: StaticPlayerData[] = [
  {
    id: 8439,
    name: 'Aaron Rodgers',
    teamLogo: '../assets/NFL_Icons/Steelers.png',
    wins: 5,
    losses: 3,
    lastFive: [1, 0, 0, 1, 1],
    injured: false,
    weapons: 7,
    coaching: 9,
    oline: 7,
    defense: 9,
    responsibility: 10,
  },
  {
    id: 3052587,
    name: 'Baker Mayfield',
    teamLogo: '../assets/NFL_Icons/Bucs.png',
    wins: 6,
    losses: 2,
    lastFive: [1, 0, 1, 1, 0],
    injured: false,
    weapons: 10,
    coaching: 7,
    oline: 7,
    defense: 8,
    responsibility: 10,
  },
  {
    id: 4426338,
    name: 'Bo Nix',
    teamLogo: '../assets/NFL_Icons/Broncos.png',
    wins: 7,
    losses: 2,
    lastFive: [1, 1, 1, 1, 1],
    injured: false,
    weapons: 7,
    coaching: 9,
    oline: 8,
    defense: 12,
    responsibility: 7,
  },
  {
    id: 4685720,
    name: 'Bryce Young',
    teamLogo: '../assets/NFL_Icons/Panthers.png',
    wins: 5,
    losses: 3,
    lastFive: [1, 1, 1, 1, 0],
    injured: false,
    weapons: 6,
    coaching: 6,
    oline: 7,
    defense: 8,
    responsibility: 6,
  },
  {
    id: 2573079,
    name: 'Carson Wentz',
    teamLogo: '../assets/NFL_Icons/Vikings.png',
    wins: 2,
    losses: 3,
    lastFive: [0, 0, 1, 0, 1],
    injured: false,
    weapons: 12,
    coaching: 9,
    oline: 9,
    defense: 12,
    responsibility: 7,
  },
  {
    id: 4688380,
    name: 'Cam Ward',
    teamLogo: '../assets/NFL_Icons/Titans.png',
    wins: 1,
    losses: 8,
    lastFive: [0, 0, 0, 0, 1],
    injured: false,
    weapons: 3,
    coaching: 5,
    oline: 3,
    defense: 9,
    responsibility: 3,
  },
  {
    id: 4431611,
    name: 'Caleb Williams',
    teamLogo: '../assets/NFL_Icons/Bears.png',
    wins: 5,
    losses: 3,
    lastFive: [1, 0, 1, 1, 1],
    injured: false,
    weapons: 8,
    coaching: 4,
    oline: 5,
    defense: 9,
    responsibility: 9,
  },
  {
    id: 4432577,
    name: 'C.J. Stroud',
    teamLogo: '../assets/NFL_Icons/Texans.png',
    wins: 3,
    losses: 5,
    lastFive: [0, 1, 0, 1, 1],
    injured: false,
    weapons: 9,
    coaching: 8,
    oline: 9,
    defense: 7,
    responsibility: 9,
  },
  {
    id: 2577417,
    name: 'Dak Prescott',
    teamLogo: '../assets/NFL_Icons/Cowboys.png',
    wins: 3,
    losses: 5,
    ties: 1,
    lastFive: [0, 0, 1, 0, 1],
    injured: false,
    weapons: 10,
    coaching: 8,
    oline: 9,
    defense: 2,
    responsibility: 9,
  },
  {
    id: 3917792,
    name: 'Daniel Jones',
    teamLogo: '../assets/NFL_Icons/Colts.png',
    wins: 7,
    losses: 2,
    lastFive: [0, 1, 1, 1, 1],
    injured: false,
    weapons: 10,
    coaching: 9,
    oline: 12,
    defense: 9,
    responsibility: 6,
  },
  {
    id: 4431452,
    name: 'Drake Maye',
    teamLogo: '../assets/NFL_Icons/Patriots.png',
    wins: 7,
    losses: 2,
    lastFive: [1, 1, 1, 1, 1],
    injured: false,
    weapons: 5,
    coaching: 10,
    oline: 6,
    defense: 8,
    responsibility: 7,
  },
  {
    id: 15864,
    name: 'Geno Smith',
    teamLogo: '../assets/NFL_Icons/Raiders.png',
    wins: 2,
    losses: 6,
    lastFive: [0, 0, 1, 0, 0],
    injured: false,
    weapons: 8,
    coaching: 7,
    oline: 3,
    defense: 5,
    responsibility: 6,
  },
  {
    id: 4040715,
    name: 'Jalen Hurts',
    teamLogo: '../assets/NFL_Icons/Eagles.png',
    wins: 6,
    losses: 2,
    lastFive: [1, 1, 0, 0, 1],
    injured: false,
    weapons: 10,
    coaching: 10,
    oline: 11,
    defense: 9,
    responsibility: 8,
  },
  {
    id: 3046779,
    name: 'Jared Goff',
    teamLogo: '../assets/NFL_Icons/Lions.png',
    wins: 5,
    losses: 3,
    lastFive: [0, 1, 0, 1, 1],
    injured: false,
    weapons: 9,
    coaching: 9,
    oline: 12,
    defense: 10,
    responsibility: 8,
  },
  {
    id: 4689114,
    name: 'Jaxson Dart',
    teamLogo: '../assets/NFL_Icons/Giants.png',
    wins: 2,
    losses: 4,
    lastFive: [0, 0, 0, 1, 0],
    injured: false,
    weapons: 4,
    coaching: 8,
    oline: 6,
    defense: 4,
    responsibility: 6,
  },
  {
    id: 4426348,
    name: 'Jayden Daniels',
    teamLogo: '../assets/NFL_Icons/Commanders.png',
    wins: 2,
    losses: 4,
    lastFive: [0, 0, 0, 1, 0],
    injured: false,
    weapons: 8,
    coaching: 4,
    oline: 8,
    defense: 4,
    responsibility: 8,
  },
  {
    id: 11252,
    name: 'Joe Flacco',
    teamLogo: '../assets/NFL_Icons/Bengals.png',
    wins: 2,
    losses: 6,
    lastFive: [0, 0, 1, 0, 0],
    injured: false,
    weapons: 11,
    coaching: 6,
    oline: 4,
    defense: 2,
    responsibility: 8,
  },
  {
    id: 4036378,
    name: 'Jordan Love',
    teamLogo: '../assets/NFL_Icons/Packers.png',
    wins: 5,
    losses: 2,
    ties: 1,
    lastFive: [0, 1, 1, 1, 0.5],
    injured: false,
    weapons: 7,
    coaching: 10,
    oline: 10,
    defense: 7,
    responsibility: 8,
  },
  {
    id: 3918298,
    name: 'Josh Allen',
    teamLogo: '../assets/NFL_Icons/Bills.png',
    wins: 6,
    losses: 2,
    lastFive: [1, 1, 0, 0, 1],
    injured: false,
    weapons: 6,
    coaching: 6,
    oline: 10,
    defense: 8,
    responsibility: 12,
  },
  {
    id: 4362887,
    name: 'Justin Fields',
    teamLogo: '../assets/NFL_Icons/Jets.png',
    wins: 1,
    losses: 6,
    lastFive: [1, 0, 0, 0, 0],
    injured: false,
    weapons: 5,
    coaching: 4,
    oline: 4,
    defense: 5,
    responsibility: 4,
  },
  {
    id: 4038941,
    name: 'Justin Herbert',
    teamLogo: '../assets/NFL_Icons/Chargers.png',
    wins: 6,
    losses: 2,
    lastFive: [1, 1, 0, 1, 0],
    injured: false,
    weapons: 7,
    coaching: 9,
    oline: 6,
    defense: 8,
    responsibility: 9,
  },
  {
    id: 3917315,
    name: 'Kyler Murray',
    teamLogo: '../assets/NFL_Icons/Cardinals.png',
    wins: 2,
    losses: 3,
    lastFive: [0, 0, 0, 1, 1],
    injured: true,
    weapons: 6,
    coaching: 6,
    oline: 5,
    defense: 4,
    responsibility: 9,
  },
  {
    id: 3916387,
    name: 'Lamar Jackson',
    teamLogo: '../assets/NFL_Icons/Ravens.png',
    wins: 2,
    losses: 3,
    lastFive: [1, 0, 0, 1, 0],
    injured: false,
    weapons: 8,
    coaching: 10,
    oline: 7,
    defense: 3,
    responsibility: 12,
  },
  {
    id: 4241464,
    name: 'Mac Jones',
    teamLogo: '../assets/NFL_Icons/49ers.png',
    wins: 5,
    losses: 2,
    lastFive: [1, 0, 1, 0, 1],
    injured: false,
    weapons: 10,
    coaching: 11,
    oline: 9,
    defense: 8,
    responsibility: 4,
  },
  {
    id: 12483,
    name: 'Matthew Stafford',
    teamLogo: '../assets/NFL_Icons/Rams.png',
    wins: 6,
    losses: 2,
    lastFive: [1, 1, 1, 0, 1],
    injured: false,
    weapons: 11,
    coaching: 11,
    oline: 6,
    defense: 6,
    responsibility: 10,
  },
  {
    id: 4360423,
    name: 'Michael Penix Jr',
    teamLogo: '../assets/NFL_Icons/Falcons.png',
    wins: 3,
    losses: 4,
    lastFive: [0, 0, 1, 1, 0],
    injured: false,
    weapons: 9,
    coaching: 5,
    oline: 7,
    defense: 5,
    responsibility: 8,
  },
  {
    id: 3139477,
    name: 'Patrick Mahomes II',
    teamLogo: '../assets/NFL_Icons/Chiefs.png',
    wins: 5,
    losses: 4,
    lastFive: [0, 1, 1, 1, 0],
    injured: false,
    weapons: 7,
    coaching: 12,
    oline: 10,
    defense: 10,
    responsibility: 11,
  },
  {
    id: 3912547,
    name: 'Sam Darnold',
    teamLogo: '../assets/NFL_Icons/Seahawks.png',
    wins: 6,
    losses: 2,
    lastFive: [1, 1, 1, 0, 1],
    injured: false,
    weapons: 9,
    coaching: 9,
    oline: 9,
    defense: 9,
    responsibility: 8,
  },
  {
    id: 4426339,
    name: 'Spencer Rattler',
    teamLogo: '../assets/NFL_Icons/Saints.png',
    wins: 1,
    losses: 7,
    lastFive: [0, 0, 0, 1, 0],
    injured: false,
    weapons: 8,
    coaching: 5,
    oline: 6,
    defense: 6,
    responsibility: 8,
  },
  {
    id: 4360310,
    name: 'Trevor Lawrence',
    teamLogo: '../assets/NFL_Icons/Jaguars.png',
    wins: 5,
    losses: 3,
    lastFive: [1, 0, 0, 1, 1],
    injured: false,
    weapons: 5,
    coaching: 7,
    oline: 3,
    defense: 2,
    responsibility: 8,
  },
  {
    id: 4241479,
    name: 'Tua Tagovailoa',
    teamLogo: '../assets/NFL_Icons/Dolphins.png',
    wins: 2,
    losses: 7,
    lastFive: [0, 1, 0, 0, 0],
    injured: false,
    weapons: 12,
    coaching: 9,
    oline: 8,
    defense: 6,
    responsibility: 7,
  },
];
