name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.9.0" # Change this to the Node.js version you're using

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Change this if your build command is different

      - name: Install Firebase CLI
        run: npm install -g firebase-tools # Install Firebase CLI globally

      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
